<<<<<<< HEAD
"""
This is a setup.py script generated by py2applet
=======
'''
    QBI Meunier Tracker APP: setup.py (Windows 64bit MSI)
    *******************************************************************************
    Copyright (C) 2015  QBI Software, The University of Queensland

    This program is free software; you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation; either version 2 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.
'''
#
# Step 1. Build first 
#   python setup.py build
# View build dir contents
# Step 2. Create MSI distribution (Windows) 
#   python setup.py bdist_msi
# View dist dir contents
>>>>>>> origin/master

Usage:
    python3 setup.py py2app
    
    Manually copy Qt frameworks
    cp -R /Applications/Qt5/5.5/clang_64/lib/QtCore.framework 
    	dist/trackerapp.app/Contents/Frameworks
    cp -R /Applications/Qt5/5.5/clang_64/lib/QtGui.framework 
    	dist/trackerapp.app/Contents/Frameworks
    cp -R /Applications/Qt5/5.5/clang_64/lib/QtWidgets.framework 
    	dist/trackerapp.app/Contents/Frameworks
    	
    [ref: http://doc.qt.io/qt-4.8/deployment-mac.html]
"""
from setuptools import setup
from plistlib import Plist

#Add info to MacOSX plist
#plist = Plist.fromFile('Info.plist')
plist= dict(CFBundleDisplayName='QBI Meunier Trackerapp',
	NSHumanReadableCopyright='Copyright (c) 2015 Queensland Brain Institute',
	CFBundleTypeIconFile='resources/target.icns',
	CFBundleVersion='2.2')

APP = ['trackerapp.py']
DATA_FILES = ['resources','tracker.ui','tracker_help.ui','tracker_progress.ui']
OPTIONS = {'argv_emulation': True, 
	'plist': plist,
	'iconfile':'resources/target.icns',
	'includes' : ['sip', 'PyQt5','PyQt5.QtCore', 'PyQt5.QtGui',
		'PyQt5.QtWidgets','PyQt5.uic.port_v3'],
	'excludes' : ['PyQt5.QtDesigner','PyQt5.QtNetwork','PyQt5.QtOpenGL',
		'PyQt5.QtScript','PyQt5.QtTest','PyQt5.QtSql','PyQt5.QtWebKit',
		'PyQt5.QtXml','PyQt5.phonon','PyQt5.uic.port_v2'],
	'packages': ['shapely','scipy'],
	
}

setup(
<<<<<<< HEAD
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
=======
        name = application_title,
        version = "3.0",
        description = "Tracker script with GUI",
        author="Liz Cooper-Williams, QBI",
        author_email="e.cooperwilliams@uq.edu.au",
        maintainer="QBI Custom Software, UQ",
        maintainer_email="qbi@uq.edu.au",
        url="http://github.com/QBI-Microscopy/Tracking",
        license="GNU General Public License (GPL)",
        options = {"build_exe" : build_exe_options,},
        executables = [Executable(main_python_file, base = base, targetName="trackerapp.exe",icon="resources/target.ico",
        shortcutName=application_title, shortcutDir="DesktopFolder")])
>>>>>>> origin/master
