"""
This is a setup.py script generated by py2applet

Usage:
    python3 setup.py py2app
    
    Manually copy Qt frameworks
    cp -R /Applications/Qt5/5.5/clang_64/lib/QtCore.framework 
    	dist/trackerapp.app/Contents/Frameworks
    cp -R /Applications/Qt5/5.5/clang_64/lib/QtGui.framework 
    	dist/trackerapp.app/Contents/Frameworks
    cp -R /Applications/Qt5/5.5/clang_64/lib/QtWidgets.framework 
    	dist/trackerapp.app/Contents/Frameworks
    	
    [ref: http://doc.qt.io/qt-4.8/deployment-mac.html]
"""
from setuptools import setup
from plistlib import Plist

#Add info to MacOSX plist
#plist = Plist.fromFile('Info.plist')
plist= dict(CFBundleDisplayName='QBI Meunier Trackerapp',
	NSHumanReadableCopyright='Copyright (c) 2015 Queensland Brain Institute',
	CFBundleTypeIconFile='resources/target.icns',
	CFBundleVersion='2.2')

APP = ['trackerapp.py']
DATA_FILES = ['resources','tracker.ui','tracker_help.ui','tracker_progress.ui']
OPTIONS = {'argv_emulation': True, 
	'plist': plist,
	'iconfile':'resources/target.icns',
	'includes' : ['sip', 'PyQt5','PyQt5.QtCore', 'PyQt5.QtGui',
		'PyQt5.QtWidgets','PyQt5.uic.port_v3'],
	'excludes' : ['PyQt5.QtDesigner','PyQt5.QtNetwork','PyQt5.QtOpenGL',
		'PyQt5.QtScript','PyQt5.QtTest','PyQt5.QtSql','PyQt5.QtWebKit',
		'PyQt5.QtXml','PyQt5.phonon','PyQt5.uic.port_v2'],
	'packages': ['shapely','scipy'],
	
}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
